version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: framer-motion
    versions:
    - 3.10.0
    - 3.10.2
    - 3.10.3
    - 3.10.5
    - 3.10.6
    - 3.2.1
    - 3.3.0
    - 3.5.1
    - 3.5.2
    - 3.6.5
    - 3.6.7
    - 3.7.0
    - 3.8.1
    - 3.9.1
    - 3.9.2
    - 4.0.0
    - 4.0.2
    - 4.0.3
    - 4.1.10
    - 4.1.2
    - 4.1.3
    - 4.1.5
    - 4.1.6
    - 4.1.9
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: react-hook-form
    versions:
    - 6.14.2
    - 6.15.1
    - 6.15.2
    - 6.15.3
    - 6.15.4
    - 6.15.5
    - 6.15.6
    - 7.0.0
    - 7.0.3
    - 7.0.4
    - 7.0.7
    - 7.1.0
    - 7.2.0
    - 7.2.1
    - 7.2.3
    - 7.3.4
  - dependency-name: styled-icons
    versions:
    - 10.26.0
    - 10.27.0
    - 10.28.0
    - 10.29.0
    - 10.30.0
    - 10.31.0
    - 10.32.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: next
    versions:
    - 10.0.5
    - 10.0.6
    - 10.0.7
    - 10.0.8
    - 10.0.9
    - 10.1.2
    - 10.1.3
  - dependency-name: "@types/styled-components"
    versions:
    - 5.1.7
    - 5.1.8
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: react-spinners
    versions:
    - 0.10.4
